export interface IndianState {
  code: string;
  name: string;
}

export const INDIAN_STATES: IndianState[] = [
  { code: '08', name: 'Rajasthan' },
  { code: '27', name: 'Maharashtra' },
  { code: '07', name: 'Delhi' },
  { code: '29', name: 'Karnataka' },
  { code: '33', name: 'Tamil Nadu' },
  { code: '09', name: 'Uttar Pradesh' },
  { code: '24', name: 'Gujarat' },
  { code: '36', name: 'Telangana' },
  { code: '19', name: 'West Bengal' },
  { code: '06', name: 'Haryana' },
  { code: '03', name: 'Punjab' },
  { code: '32', name: 'Kerala' },
  { code: '10', name: 'Bihar' },
  { code: '23', name: 'Madhya Pradesh' },
  { code: '37', name: 'Andhra Pradesh' },
  { code: '21', name: 'Odisha' },
  { code: '20', name: 'Jharkhand' },
  { code: '22', name: 'Chhattisgarh' },
  { code: '05', name: 'Uttarakhand' },
  { code: '02', name: 'Himachal Pradesh' },
  { code: '01', name: 'Jammu and Kashmir' },
  { code: '30', name: 'Goa' },
  { code: '18', name: 'Assam' },
  { code: '04', name: 'Chandigarh' },
  { code: '34', name: 'Puducherry' },
  { code: '38', name: 'Ladakh' },
  { code: '11', name: 'Sikkim' },
  { code: '16', name: 'Tripura' },
  { code: '17', name: 'Meghalaya' },
  { code: '14', name: 'Manipur' },
  { code: '13', name: 'Nagaland' },
  { code: '12', name: 'Arunachal Pradesh' },
  { code: '15', name: 'Mizoram' },
  { code: '35', name: 'Andaman and Nicobar Islands' },
  { code: '26', name: 'Dadra and Nagar Haveli and Daman and Diu' },
  { code: '31', name: 'Lakshadweep' },
  { code: '97', name: 'Other Territory' },
];
