export const ROUTES = {
  HOME: '/',
  ABOUT: '/about',
  DOCS: '/docs',
  LOGIN: '/login',
  SIGNUP: '/signup',
  DASHBOARD: '/dashboard',
  GST: {
    ROOT: '/gst',
    TEMPLATES: '/gst/templates',
    CUSTOMIZE: '/gst/templates/:id/customize',
    LETA: '/gst/leta',
  },
  INCOME_TAX: '/income-tax',
  INCOME_TAX_LETA: '/income-tax/leta',
  FEMA: '/fema',
  FEMA_LETA: '/fema/leta',
  COMPANY_LAW: '/company-law',
  COMPANY_LAW_LETA: '/company-law/leta',
  ADMIN: {
    TEMPLATES: '/admin/templates',
    UPLOAD: '/admin/upload',
  },
  RESPONSES: '/responses',
};
