import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { FileText, Shield, AlertTriangle, RotateCcw, CreditCard, Lock } from 'lucide-react';

const CONTACT_EMAIL = 'contact@letatec.com';
const COMPANY_ADDRESS = 'LG-32 Jaipur Electronics Market, Riddhi Siddhi Chowraha, Gopal Pura Bypass, Jaipur - 303019';

const tabs = [
  { id: 'terms',      label: 'Terms & Conditions',       icon: FileText,      lastUpdated: '13 July 2026' },
  { id: 'privacy',    label: 'Privacy Policy',            icon: Shield,        lastUpdated: 'July 2026' },
  { id: 'disclaimer', label: 'Disclaimer',                icon: AlertTriangle, lastUpdated: 'July 2026' },
  { id: 'refund',     label: 'Refund & Cancellation',     icon: RotateCcw,     lastUpdated: 'July 2026' },
  { id: 'subscription', label: 'Subscription Terms',      icon: CreditCard,    lastUpdated: 'July 2026' },
  { id: 'encryption', label: 'Data Encryption Policy',    icon: Lock,          lastUpdated: 'July 2026' },
] as const;

type TabId = (typeof tabs)[number]['id'];

// ─── Shared primitives ───────────────────────────────────────────────────────

const Section: React.FC<{ title: string; children: React.ReactNode }> = ({ title, children }) => (
  <div className="mb-8">
    <h3 className="font-display font-semibold text-base text-white uppercase tracking-wider mb-3 pb-2"
      style={{ borderBottom: '1px solid rgba(79,183,197,0.15)' }}>
      {title}
    </h3>
    <div className="text-sm font-light leading-relaxed text-[#A7B3C2] space-y-2">
      {children}
    </div>
  </div>
);

const Ul: React.FC<{ items: string[] }> = ({ items }) => (
  <ul className="ml-4 space-y-1.5">
    {items.map((item, i) => (
      <li key={i} className="flex gap-2">
        <span style={{ color: '#4FB7C5' }} className="mt-1 flex-shrink-0">—</span>
        <span>{item}</span>
      </li>
    ))}
  </ul>
);

const Warning: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <div className="flex gap-3 px-4 py-3 rounded-xl my-3"
    style={{ background: 'rgba(245,158,11,0.06)', border: '1px solid rgba(245,158,11,0.2)' }}>
    <AlertTriangle size={14} className="flex-shrink-0 mt-0.5" style={{ color: '#F59E0B' }} />
    <span className="text-xs text-[#A7B3C2]">{children}</span>
  </div>
);

const Important: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <div className="flex gap-3 px-4 py-3 rounded-xl my-3"
    style={{ background: 'rgba(79,183,197,0.05)', border: '1px solid rgba(79,183,197,0.2)' }}>
    <Shield size={14} className="flex-shrink-0 mt-0.5" style={{ color: '#4FB7C5' }} />
    <span className="text-xs text-[#A7B3C2]">{children}</span>
  </div>
);

// ─── Document content components ─────────────────────────────────────────────

const TermsContent = () => (
  <>
    <p className="text-sm text-[#A7B3C2] leading-relaxed mb-6">
      Welcome to <strong className="text-white">letatec.com</strong> ("Platform"), operated by{' '}
      <strong className="text-white">LETATEC AI Technologies Private Limited</strong> ("Company", "we", "us", or "our").
      By accessing or using this Platform, you agree to the following Terms and Conditions.
    </p>

    <Section title="1. Nature of Services">
      <p>The Platform provides AI-powered tools for:</p>
      <Ul items={['Tax research and analysis', 'Legal drafting assistance', 'Document generation and suggestions', 'Document Download']} />
      <Important>The Platform does not provide professional legal or tax advice. Outputs are for informational and assistance purposes only.</Important>
    </Section>

    <Section title="2. No Professional Advice Disclaimer">
      <p>The content generated by the Platform:</p>
      <Ul items={[
        'Is not a substitute for advice from a qualified lawyer, chartered accountant, or tax professional',
        'May not be accurate, complete, or up to date',
        'Should not be solely relied upon for decision-making',
      ]} />
      <p className="mt-2">Users are strongly advised to seek professional consultation before acting on any output.</p>
    </Section>

    <Section title="3. User Responsibilities">
      <p>You agree:</p>
      <Ul items={[
        'To use the Platform only for lawful purposes',
        'Not to input confidential, sensitive, or personal data without proper authorization',
        'To verify all AI-generated outputs before use',
      ]} />
      <p className="mt-2">You are solely responsible for how you use the generated content.</p>
    </Section>

    <Section title="4. Accuracy and Limitations">
      <p>While we strive to provide reliable outputs:</p>
      <Ul items={[
        'AI-generated content may contain errors or omissions',
        'Laws and tax regulations change frequently',
        'Jurisdiction-specific nuances may not always be captured',
      ]} />
      <p className="mt-2">We do not guarantee accuracy, reliability, or suitability.</p>
    </Section>

    <Section title="5. Intellectual Property">
      <Ul items={[
        'The Platform, including software, design, and algorithms, is owned by the Company',
        'Users retain rights to their inputs',
        'Generated outputs may be used by users, subject to applicable laws',
      ]} />
      <p className="mt-2">You may not reverse engineer, copy, or redistribute the Platform without permission.</p>
    </Section>

    <Section title="6. Data Usage and Privacy">
      <Ul items={[
        'Inputs may be processed to improve the Platform',
        'We take reasonable steps to protect user data',
        'Please review our Privacy Policy for details',
      ]} />
      <Warning>Avoid sharing highly sensitive or privileged information.</Warning>
    </Section>

    <Section title="7. Limitation of Liability">
      <p>To the fullest extent permitted by law:</p>
      <Ul items={[
        'The Company is not liable for any direct, indirect, or consequential damages',
        'This includes losses arising from reliance on AI-generated outputs',
      ]} />
      <p className="mt-2">Use of the Platform is at your own risk.</p>
    </Section>

    <Section title="8. Indemnification">
      <p>You agree to indemnify and hold harmless the Company from:</p>
      <Ul items={['Any claims arising from your use of the Platform', 'Misuse or reliance on generated outputs']} />
    </Section>

    <Section title="9. Service Availability">
      <p>We do not guarantee:</p>
      <Ul items={['Continuous or uninterrupted access', 'Error-free operation']} />
      <p className="mt-2">We may modify or discontinue features at any time.</p>
    </Section>

    <Section title="10. Termination">
      <p>We reserve the right to:</p>
      <Ul items={['Suspend or terminate access for violations of these Terms', 'Remove content or restrict usage without prior notice']} />
    </Section>

    <Section title="11. Governing Law and Jurisdiction">
      <p>These Terms shall be governed by the laws of <strong className="text-white">India</strong>.</p>
      <p>Any disputes shall be subject to the jurisdiction of courts located in <strong className="text-white">Jaipur</strong>.</p>
    </Section>

    <Section title="12. Updates to Terms">
      <p>We may update these Terms periodically. Continued use of the Platform constitutes acceptance of revised Terms.</p>
    </Section>

    <Section title="13. Contact Information">
      <p>For any queries, contact:</p>
      <p>Email: <a href={`mailto:${CONTACT_EMAIL}`} className="text-[#4FB7C5] hover:underline">{CONTACT_EMAIL}</a></p>
      <p>Address: {COMPANY_ADDRESS}</p>
    </Section>

    <Important>By using this Platform, you acknowledge that you have read, understood, and agreed to these Terms and Conditions.</Important>
  </>
);

const PrivacyContent = () => (
  <>
    <p className="text-sm text-[#A7B3C2] leading-relaxed mb-6">
      This Privacy Policy describes how <strong className="text-white">LETATEC AI Technologies Private Limited</strong> collects,
      uses, and protects your data when you use <strong className="text-white">LETATEC</strong> ("Platform").
    </p>

    <Section title="1. Legal Compliance">
      <p>We comply with:</p>
      <Ul items={['Information Technology Act, 2000', 'Digital Personal Data Protection Act, 2023', 'Applicable Indian data protection and cybersecurity rules']} />
    </Section>

    <Section title="2. Information We Collect">
      <p>We may collect:</p>
      <Ul items={['Name, email, phone number', 'Login credentials', 'Usage data (queries, drafts, prompts)', 'Device and browser information']} />
      <Warning>Do not upload: highly confidential client data, privileged legal communications, or sensitive personal data unless necessary.</Warning>
    </Section>

    <Section title="3. Purpose of Data Collection">
      <p>We use your data to:</p>
      <Ul items={['Provide AI-generated tax and legal assistance', 'Improve accuracy and system performance', 'Ensure platform security', 'Communicate updates and support']} />
    </Section>

    <Section title="4. AI Data Processing Disclosure">
      <Ul items={['Inputs provided may be processed by AI systems', 'Outputs are generated probabilistically and may not be unique', 'Data may be used in anonymized form for model improvement']} />
    </Section>

    <Section title="5. Data Sharing">
      <p><strong className="text-white">We do NOT sell your data.</strong></p>
      <p className="mt-1">We may share data with:</p>
      <Ul items={['Cloud service providers (secure processing)', 'Legal authorities if required under Indian law']} />
    </Section>

    <Section title="6. Data Retention">
      <Ul items={['Data is retained only as long as necessary', 'You may request deletion of your data']} />
    </Section>

    <Section title="7. User Rights (India)">
      <p>Under applicable law, you have the right to:</p>
      <Ul items={['Access your data', 'Request correction or deletion', 'Withdraw consent']} />
      <p className="mt-2">Contact us at: <a href={`mailto:${CONTACT_EMAIL}`} className="text-[#4FB7C5] hover:underline">{CONTACT_EMAIL}</a></p>
    </Section>

    <Section title="8. Security Measures">
      <p>We implement:</p>
      <Ul items={['Encryption', 'Access controls', 'Secure servers']} />
      <p className="mt-2">However, no system is 100% secure.</p>
    </Section>

    <Section title="9. Children's Privacy">
      <p>This Platform is not intended for users under 18 years of age.</p>
    </Section>

    <Section title="10. Cross-Border Data Transfer">
      <p>Your data may be processed outside India with adequate safeguards.</p>
    </Section>

    <Section title="11. Grievance Officer">
      <p>Name: Samaksh Mathur</p>
      <p>Email: <a href={`mailto:${CONTACT_EMAIL}`} className="text-[#4FB7C5] hover:underline">{CONTACT_EMAIL}</a></p>
      <p>Address: {COMPANY_ADDRESS}</p>
    </Section>

    <Section title="12. Updates">
      <p>We may update this Privacy Policy periodically.</p>
    </Section>

    <Important>By using the Platform, you consent to this Privacy Policy.</Important>
  </>
);

const DisclaimerContent = () => (
  <>
    <p className="text-sm text-[#A7B3C2] leading-relaxed mb-6">
      The information and content generated by <strong className="text-white">LETATEC</strong> is provided on an "as is" basis.
    </p>

    <Section title="1. No Legal or Tax Advice">
      <p>This Platform:</p>
      <Ul items={['Does NOT provide legal advice', 'Does NOT provide tax consultancy services']} />
      <p className="mt-2">Use of this Platform does not create:</p>
      <Ul items={['Lawyer-client relationship', 'Chartered Accountant-client relationship', 'Any other professional relationship']} />
    </Section>

    <Section title="2. Professional Verification Required">
      <p>All outputs:</p>
      <Ul items={['Must be independently verified', 'Should be reviewed by qualified professionals']} />
    </Section>

    <Section title="3. Regulatory Compliance (India)">
      <p>This Platform operates strictly as a <strong className="text-white">technology tool</strong>, and not as a law firm or CA firm or any other law or tax firm.</p>
      <p className="mt-2">In compliance with:</p>
      <Ul items={['Bar Council of India rules (no solicitation or legal practice)', 'ICAI guidelines for chartered accountants']} />
    </Section>

    <Section title="4. Accuracy Disclaimer">
      <p>We do not guarantee:</p>
      <Ul items={['Accuracy', 'Completeness', 'Updated legal position']} />
      <p className="mt-2">Laws including GST, Income Tax, and company law change frequently.</p>
    </Section>

    <Section title="5. Limitation of Liability">
      <p>We are not liable for:</p>
      <Ul items={['Any financial loss', 'Legal consequences', 'Decisions made based on AI output']} />
    </Section>

    <Section title="6. Third-Party Content">
      <p>The Platform may reference laws, case laws, and external data. We do not guarantee their correctness.</p>
    </Section>

    <Section title="7. Use at Your Own Risk">
      <p>You agree that:</p>
      <Ul items={['You are solely responsible for usage', 'You will not rely solely on AI-generated outputs']} />
    </Section>

    <Section title="8. Jurisdiction">
      <p>This Disclaimer is governed by Indian law.</p>
    </Section>

    <Important>By using this Platform, you accept this Disclaimer.</Important>
  </>
);

const RefundContent = () => (
  <>
    <p className="text-sm text-[#A7B3C2] leading-relaxed mb-6">
      This Refund &amp; Cancellation Policy applies to all subscriptions and services offered by{' '}
      <strong className="text-white">LETATEC AI Technologies Private Limited</strong> through the Platform.
    </p>

    <Section title="1. No Refund Policy (Default SaaS Model)">
      <p>All payments made for subscriptions are <strong className="text-white">non-refundable</strong>, except where required under applicable law.</p>
    </Section>

    <Section title="2. Free Trial (If Applicable)">
      <Ul items={['Users may be offered a free trial period', 'No charges will apply during the trial', 'Once the trial ends, billing will begin automatically']} />
    </Section>

    <Section title="3. Subscription Cancellation">
      <Ul items={['Users may cancel their subscription at any time', 'Cancellation will be effective at the end of the current billing cycle', 'No partial refunds will be provided']} />
    </Section>

    <Section title="4. Exceptional Refunds">
      <p>Refunds may be considered only in the following cases:</p>
      <Ul items={['Duplicate payment', 'Technical failure preventing access (verified by Company)', 'Erroneous billing']} />
      <p className="mt-2">Refund requests must be raised within <strong className="text-white">7 days</strong> of the transaction.</p>
    </Section>

    <Section title="5. Processing of Refunds">
      <Ul items={['Approved refunds will be processed within 7–10 working days', 'Refunds will be issued to the original payment method']} />
    </Section>

    <Section title="6. Chargebacks">
      <p>Users agree not to initiate chargebacks without contacting support first. Unauthorized chargebacks may lead to account suspension.</p>
    </Section>

    <Section title="7. Contact for Refunds">
      <p>Email: <a href={`mailto:${CONTACT_EMAIL}`} className="text-[#4FB7C5] hover:underline">{CONTACT_EMAIL}</a></p>
    </Section>

    <Section title="8. Legal Compliance">
      <p>This policy complies with applicable provisions of the Consumer Protection Act, 2019.</p>
    </Section>

    <Important>By subscribing, you agree to this Refund Policy.</Important>
  </>
);

const SubscriptionContent = () => (
  <>
    <p className="text-sm text-[#A7B3C2] leading-relaxed mb-6">
      These Subscription Terms govern the use of paid services on <strong className="text-white">LETATEC</strong>.
    </p>

    <Section title="1. Plans & Pricing">
      <Ul items={['Subscription plans may be hourly, daily, weekly, monthly, quarterly, or annual', 'Pricing is displayed on the Platform and may change with notice']} />
    </Section>

    <Section title="2. Auto-Renewal">
      <Ul items={['Subscriptions automatically renew unless cancelled, or may not auto-renew depending on the plan', 'Users authorize recurring payments']} />
    </Section>

    <Section title="3. Payment Terms">
      <Ul items={['Payments must be made in advance', 'Payment must be from approved channels']} />
    </Section>

    <Section title="4. Usage Limits">
      <Ul items={['Plans may include limits (queries, documents, API usage)', 'Exceeding limits may result in additional charges or restriction']} />
    </Section>

    <Section title="5. Account Responsibility">
      <p>Users must:</p>
      <Ul items={['Maintain confidentiality of login credentials', 'Not share accounts or misuse services']} />
    </Section>

    <Section title="6. Modification of Plans">
      <p>We may:</p>
      <Ul items={['Change features', 'Update pricing (with prior notice)']} />
    </Section>

    <Section title="7. Suspension / Termination">
      <p>We may suspend accounts for:</p>
      <Ul items={['Violation of terms', 'Misuse of AI (illegal drafting, fraud, etc.)']} />
    </Section>

    <Section title="8. No Guarantee of Results">
      <p>AI outputs are probabilistic and may not always be accurate or suitable.</p>
    </Section>

    <Section title="9. Compliance with Laws">
      <p>Users agree to comply with the Information Technology Act, 2000, and applicable tax and legal regulations.</p>
    </Section>

    <Section title="10. Governing Law">
      <p>These terms are governed by Indian law.</p>
    </Section>

    <Important>By subscribing, you agree to these Subscription Terms.</Important>
  </>
);

const EncryptionContent = () => (
  <>
    <p className="text-sm text-[#A7B3C2] leading-relaxed mb-6">
      This Data Encryption Policy outlines how <strong className="text-white">LETATEC AI Technologies Private Limited</strong> secures
      data within the Platform, an AI-powered system for tax research and legal drafting.
    </p>

    <Section title="1. Purpose">
      <Ul items={['Protect user data from unauthorized access', 'Ensure confidentiality, integrity, and availability of information', 'Comply with applicable Indian data protection and cybersecurity laws']} />
    </Section>

    <Section title="2. Scope">
      <p>This Policy applies to:</p>
      <Ul items={['All user data (inputs, prompts, documents, account data)', 'Internal systems and databases', 'Data in transit and at rest', 'Employees, contractors, and third-party vendors']} />
    </Section>

    <Section title="3. Encryption Standards">
      <p className="font-semibold text-white mb-2">3.1 Data in Transit</p>
      <Ul items={['All data transmitted between users and the Platform is encrypted using TLS 1.2 or higher', 'HTTPS is enforced across all endpoints']} />
      <p className="font-semibold text-white mt-4 mb-2">3.2 Data at Rest</p>
      <Ul items={['Sensitive data stored in databases and storage systems is encrypted using AES-256']} />
      <p className="font-semibold text-white mt-4 mb-2">3.3 End-to-End Considerations</p>
      <Ul items={['Where applicable, additional encryption layers may be used for highly sensitive workflows']} />
      <Warning>Users are advised not to upload privileged or highly confidential data unless necessary.</Warning>
    </Section>

    <Section title="4. Key Management">
      <Ul items={['Encryption keys are stored securely using managed key management systems (KMS)', 'Keys are access-controlled and rotated periodically', 'Access to keys is restricted to authorized personnel only']} />
    </Section>

    <Section title="5. Access Controls">
      <Ul items={['Role-based access control (RBAC) is implemented', 'Multi-factor authentication (MFA) is enforced for administrative access', 'All access to encrypted data is logged and monitored']} />
    </Section>

    <Section title="6. Data Masking & Minimization">
      <Ul items={['Sensitive data may be masked or tokenized where feasible', 'Only necessary data is collected and retained']} />
    </Section>

    <Section title="7. Third-Party Security">
      <p>Third-party service providers must follow industry-standard encryption practices and comply with applicable data protection laws. Data Processing Agreements (DPAs) are executed where required.</p>
    </Section>

    <Section title="8. Backup & Recovery">
      <Ul items={['Encrypted backups are maintained regularly', 'Backup data is stored securely and tested periodically for recovery']} />
    </Section>

    <Section title="9. Incident Response">
      <p>In case of a data breach:</p>
      <Ul items={['Immediate containment and investigation will be initiated', 'Affected users and authorities will be notified as required under law', 'Corrective actions will be implemented']} />
    </Section>

    <Section title="10. Employee Responsibilities">
      <Ul items={['Employees must follow secure data handling practices', 'Unauthorized sharing or storage of data is strictly prohibited']} />
    </Section>

    <Section title="11. Compliance & Audit">
      <Ul items={['Regular security audits and vulnerability assessments are conducted', 'Encryption practices are reviewed periodically']} />
    </Section>

    <Section title="12. User Responsibilities">
      <p>Users should:</p>
      <Ul items={['Use secure passwords', 'Avoid sharing sensitive or privileged legal/tax data unnecessarily', 'Log out from shared devices']} />
    </Section>

    <Section title="13. Contact Information">
      <p>Email: <a href={`mailto:${CONTACT_EMAIL}`} className="text-[#4FB7C5] hover:underline">{CONTACT_EMAIL}</a></p>
    </Section>

    <Important>By using the Platform, you acknowledge and accept this Data Encryption Policy.</Important>
  </>
);

const contentMap: Record<TabId, React.ReactNode> = {
  terms:        <TermsContent />,
  privacy:      <PrivacyContent />,
  disclaimer:   <DisclaimerContent />,
  refund:       <RefundContent />,
  subscription: <SubscriptionContent />,
  encryption:   <EncryptionContent />,
};

// ─── Main page ───────────────────────────────────────────────────────────────

const LegalPolicies: React.FC = () => {
  const [activeTab, setActiveTab] = useState<TabId>('terms');

  const active = tabs.find(t => t.id === activeTab)!;

  return (
    <div className="min-h-screen bg-[#000000]">

      {/* Header */}
      <div className="pt-[140px] pb-16 px-4 sm:px-6 text-center bg-[#0F1722] border-b border-white/[0.04]">
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.4 }}
        >
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full mb-5 font-mono text-[10px] uppercase tracking-widest"
            style={{ background: 'rgba(79,183,197,0.08)', border: '1px solid rgba(79,183,197,0.2)', color: '#4FB7C5' }}>
            <Shield size={11} />
            Legal &amp; Compliance
          </div>
          <h1 className="font-display font-bold text-4xl md:text-5xl mb-4 tracking-tight text-white uppercase">
            Legal Policies
          </h1>
          <p className="text-base font-light max-w-xl mx-auto text-[#A7B3C2]">
            LETATEC AI Technologies Private Limited — governing terms, data practices, and platform policies.
          </p>
        </motion.div>
      </div>

      {/* Tab navigation */}
      <div className="sticky top-0 z-20 bg-[#000000] border-b border-white/[0.05]">
        <div className="max-w-5xl mx-auto px-4 overflow-x-auto">
          <div className="flex gap-1 py-2 min-w-max">
            {tabs.map(tab => {
              const Icon = tab.icon;
              const isActive = activeTab === tab.id;
              return (
                <button
                  key={tab.id}
                  onClick={() => setActiveTab(tab.id)}
                  className="flex items-center gap-1.5 px-3 py-2 rounded-lg text-xs font-mono transition-all duration-150 whitespace-nowrap"
                  style={{
                    background: isActive ? 'rgba(79,183,197,0.1)' : 'transparent',
                    color: isActive ? '#4FB7C5' : '#6B7280',
                    border: isActive ? '1px solid rgba(79,183,197,0.25)' : '1px solid transparent',
                  }}
                >
                  <Icon size={12} />
                  {tab.label}
                </button>
              );
            })}
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-5xl mx-auto px-4 sm:px-6 py-12">
        <AnimatePresence mode="wait">
          <motion.div
            key={activeTab}
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -6 }}
            transition={{ duration: 0.18 }}
          >
            {/* Document header */}
            <div className="flex items-start justify-between mb-8 pb-6"
              style={{ borderBottom: '1px solid rgba(79,183,197,0.1)' }}>
              <div>
                <h2 className="font-display font-bold text-2xl text-white uppercase tracking-wide mb-1">
                  {active.label}
                </h2>
                <span className="text-xs font-mono text-[#6B7280]">
                  Last Updated: {active.lastUpdated} · LETATEC AI Technologies Private Limited
                </span>
              </div>
              <active.icon size={28} style={{ color: 'rgba(79,183,197,0.3)', flexShrink: 0 }} />
            </div>

            {/* Document body */}
            <div className="rounded-2xl p-8"
              style={{ background: '#0A0F18', border: '1px solid rgba(79,183,197,0.08)' }}>
              {contentMap[activeTab]}
            </div>
          </motion.div>
        </AnimatePresence>
      </div>
    </div>
  );
};

export default LegalPolicies;
