import logging
from dataclasses import dataclass, field
from typing import List, Dict, Any, Tuple, Optional

from app.retrieval.reference_resolver import ReferenceResolver, LegalReference

logger = logging.getLogger("citation_validator")


@dataclass
class CitationValidationReport:
    is_valid: bool
    verdict: str                     # PASS | REPAIR | BLOCK
    verified_citations: List[str]    # Display names of verified citations
    unsupported_citations: List[str] # Citations generated by LLM not backed by retrieved chunks
    available_citations: List[str]   # Canonical references available in retrieved evidence
    notes: List[str] = field(default_factory=list)


class CitationValidator:
    """
    Performs post-synthesis validation of legal citations using canonical legal identity.
    Ensures that every Section, Rule, Circular, Notification, and Case Law cited by the LLM
    is strictly supported by the retrieved context.
    """

    @classmethod
    def audit_citations(cls, answer: str, retrieved_chunks: List[Dict[str, Any]]) -> CitationValidationReport:
        """
        Extracts canonical references from the answer and cross-checks each against
        all available references in retrieved chunks.
        """
        if not answer or not answer.strip():
            return CitationValidationReport(
                is_valid=True,
                verdict="PASS",
                verified_citations=[],
                unsupported_citations=[],
                available_citations=[],
            )

        # 1. Extract canonical citations from answer
        cited_refs = ReferenceResolver.resolve_references(answer)
        if not cited_refs:
            return CitationValidationReport(
                is_valid=True,
                verdict="PASS",
                verified_citations=[],
                unsupported_citations=[],
                available_citations=[],
                notes=["No formal legal citations detected in answer."],
            )

        # 2. Extract available references from chunks
        available_refs = ReferenceResolver.extract_available_chunk_references(retrieved_chunks)
        avail_display = [r.display_name for r in available_refs]

        verified_names: List[str] = []
        unsupported_names: List[str] = []
        notes: List[str] = []

        for cit in cited_refs:
            matched, matched_avail = ReferenceResolver.verify_citation_against_evidence(cit, available_refs)
            if matched and matched_avail:
                verified_names.append(cit.display_name)
            else:
                unsupported_names.append(cit.display_name)
                notes.append(f"Cited authority '{cit.display_name}' ({cit.canonical_key}) not found in retrieved evidence.")

        is_valid = len(unsupported_names) == 0
        verdict = "PASS" if is_valid else "BLOCK"

        if not is_valid:
            logger.warning(
                f"[CITATION_VALIDATION_FAILED] Unsupported citations: {unsupported_names} | "
                f"Verified: {verified_names} | Available: {avail_display[:10]}"
            )
        else:
            logger.debug(f"[CITATION_VALIDATION_PASSED] Verified: {verified_names}")

        return CitationValidationReport(
            is_valid=is_valid,
            verdict=verdict,
            verified_citations=verified_names,
            unsupported_citations=unsupported_names,
            available_citations=avail_display,
            notes=notes,
        )

    @classmethod
    def validate_citations(cls, answer: str, retrieved_chunks: List[Dict[str, Any]]) -> str:
        """
        Legacy entry-point compatibility. Runs audit_citations and logs diagnostics.
        """
        report = cls.audit_citations(answer, retrieved_chunks)
        return answer
